title: "curiouswendell"
author: "curiouswendell"
description: "[learning and attempting to practice OSINT]"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
# minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "curiouswendell", icon: home}
  - {file: "README.md", title: "About me", icon: eye}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
#  - {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"}
  - {title: Github, icon: github, url: "https://github.com/curiouswendell"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/curiouswendell"}

plugins:
 - jekyll-feed
